"""
Import Genetic Model Training Results to Database
Converts trained genetic model data to timetable entries in the database
"""

import json
import sys
import os
from datetime import datetime
from pathlib import Path
from bson import ObjectId
import asyncio

# Add backend directory to path
backend_dir = str(Path(__file__).parent.parent.parent)
sys.path.insert(0, backend_dir)
os.chdir(backend_dir)

from app.db.mongodb import db, connect_to_mongo, close_mongo_connection


async def import_genetic_model_to_database(model_file: str = None):
    """
    Import genetic model training results to the database as a timetable
    
    Args:
        model_file: Path to the genetic model JSON file
    """
    
    # Initialize database
    await connect_to_mongo()
    
    if model_file is None:
        # Find latest model file
        model_dir = Path(__file__).parent.parent / "models"
        model_files = list(model_dir.glob("genetic_model_*.json"))
        if not model_files:
            print("❌ No model files found in genetic_model_training/models/")
            return
        model_file = max(model_files, key=lambda x: x.stat().st_mtime)
        print(f"Using latest model: {model_file.name}")
    
    # Load model data
    model_file = Path(model_file)
    if not model_file.exists():
        print(f"❌ Model file not found: {model_file}")
        return
        
    with open(model_file, 'r') as f:
        model_data = json.load(f)
    
    print(f"\n📦 Loading genetic model from: {model_file}")
    print(f"Best fitness: {model_data['best_fitness']}")
    print(f"Generations: {model_data['generations']}")
    
    # Load training data to get courses, instructors, rooms, etc.
    data_file = Path(__file__).parent.parent / "data" / "training_data.json"
    if not data_file.exists():
        print(f"❌ Training data not found: {data_file}")
        return
        
    with open(data_file, 'r') as f:
        training_data = json.load(f)
    
    # Create timetable from genetic model
    timetable_data = {
        "name": f"AI Generated Timetable - {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "academic_year": "2025-2026",
        "semester": "5",
        "program_id": "1",
        "department_code": "CSE",
        "year": 1,
        "section": "A",
        "description": f"Generated by genetic algorithm. Best fitness: {model_data['best_fitness']:.2f}",
        "created_by_id": ObjectId("000000000000000000000001"),  # System admin
        "is_draft": False,  # Published immediately
        "constraints": model_data['constraints'],
        "metadata": {
            "genetic_algorithm": {
                "generations": model_data['generations'],
                "population_size": model_data['population_size'],
                "best_fitness": model_data['best_fitness'],
                "mutation_rate": model_data['mutation_rate'],
                "crossover_rate": model_data['crossover_rate']
            },
            "generated_at": model_data['timestamp']
        },
        "entries": []
    }
    
    # Map chromosome to timetable entries
    courses = training_data.get('courses', [])
    rooms = training_data.get('rooms', [])
    instructors = training_data.get('instructors', [])
    chromosome = model_data['best_chromosome']
    
    # Create timetable entries from chromosome
    for idx, slot_id in enumerate(chromosome[:len(courses)]):
        if idx >= len(courses):
            break
            
        course = courses[idx] if idx < len(courses) else None
        room = rooms[slot_id % len(rooms)] if rooms else None
        instructor = instructors[idx % len(instructors)] if instructors else None
        
        if course and room and instructor:
            entry = {
                "course_id": str(course['id']),
                "course_code": course['code'],
                "course_name": course['name'],
                "instructor_id": str(instructor['id']),
                "instructor_name": instructor['name'],
                "room_id": str(room['id']),
                "room_number": room['number'],
                "building": room['building'],
                "day_of_week": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"][idx % 5],
                "start_time": f"{8 + (slot_id % 9):02d}:00",
                "end_time": f"{9 + (slot_id % 9):02d}:00",
                "duration_minutes": 60,
                "batch": course.get('year', 1),
                "semester": course.get('semester', 5),
                "department": course.get('department', 'CSE')
            }
            timetable_data['entries'].append(entry)
    
    print(f"\n✓ Created {len(timetable_data['entries'])} timetable entries from genetic model")
    
    # Save to database
    result = await db.db.timetables.insert_one(timetable_data)
    timetable_id = str(result.inserted_id)
    
    print(f"✓ Timetable saved to database!")
    print(f"✓ Timetable ID: {timetable_id}")
    print(f"✓ Published: {not timetable_data['is_draft']}")
    print(f"\n📝 Use this timetable ID in frontend: {timetable_id}")
    
    return timetable_id


async def main():
    """Main execution"""
    import argparse
    
    parser = argparse.ArgumentParser(description='Import Genetic Model to Database')
    parser.add_argument('--model', type=str, help='Path to model file')
    args = parser.parse_args()
    
    try:
        await import_genetic_model_to_database(args.model)
    except Exception as e:
        print(f"❌ Error: {e}")
        import traceback
        traceback.print_exc()
    finally:
        await close_mongo_connection()


if __name__ == "__main__":
    asyncio.run(main())
